### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mikeparadinas** [csvance/FTBot#1]
Traceback (most recent call last):
  File "C:\Users\Admin\CBL.tech\MARKPVNBOT 2\FTBot-master\ftbot_discord.py", line 1, in <module>
    from ftbot import *
  File "C:\Users\Admin\CBL.tech\MARKPVNBOT 2\FTBot-master\ftbot.py", line 2, in <module>
    from search import *
  File "C:\Users\Admin\CBL.tech\MARKPVNBOT 2\FTBot-master\search.py", line 1, in <module>
    from googleapiclient.discovery import build
ImportError: No module named 'googleapiclient'

**Comment by csvance** [comment]
For some reason I never got this notification. Need to install "googleapiclient" in your python distribution. https://developers.google.com/api-client-library/python/start/installation
