### ISSUE TITLE
Can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by Atropha** [csvance/FTBot#38]
Hey. I've been trying to set this bot up for a Discord channel. I have very little experience with Python, so this was probably a bit too complex to dive into for me, but I thought I was making good progress. I got all the requirements and dependencies set up and managed to feed the training module a chunk of data that it processed just fine. But when it comes to actually connecting it throws up this:

> Traceback (most recent call last):
>   File "C:\DiscordBot\Armchair\armchair_expert.py", line 334, in <module>
>     ae.start(retrain_structure=args.retrain_structure, retrain_markov=args.retrain_markov)
>   File "C:\DiscordBot\Armchair\armchair_expert.py", line 106, in start
>     connector.start()
>   File "C:\DiscordBot\Armchair\connectors\connector_common.py", line 122, in start
>     self._scheduler.start()
>   File "C:\DiscordBot\Armchair\connectors\connector_common.py", line 101, in start
>     self._worker.start()
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\process.py", line 105, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> TypeError: can't pickle _thread.RLock objects
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
>     self = reduction.pickle.load(from_parent)
> EOFError: Ran out of input
>

**Comment by csvance** [comment]
What version of python / windows are you using just for reference? I think I see what the problem is (initializing a logger in one process that gets used by another)

**Comment by csvance** [comment]
0f3cf940b5178816e250ce7f25c0d41cf98f7ea4 should fix this, update from master and let me know if this fixes the problem for you.

**Comment by Atropha** [comment]
Oh wow, that was a fast response. Thank you!
For the record, I'm running 3.6 on Windows 10
It fixed the error and the bot starts up properly now and joins the Discord server.
It's not responding to anything, but that might be because I set something up wrong.

**Comment by csvance** [comment]
It should almost always reply on mention (@Botname), even if its just a small response when it does not have much data. How many lines of text did you initially import? If it is a small amount, try mentioning it and using words from the dataset you initially loaded in the same line.

When it started up the first time you should have seen something like this:
```
INFO:ArmchairExpert:Training begin
INFO:ArmchairExpert:Training_Preprocessing_Markov(Import)
INFO:ArmchairExpert:Training_Preprocessing_Markov(Twitter)
INFO:ArmchairExpert:Training_Preprocessing_Markov(Twitter): 0.000000%
INFO:ArmchairExpert:Training_Preprocessing_Markov(Discord)
INFO:ArmchairExpert:Training(Markov)
INFO:ArmchairExpert:Training(Markov): 0.000000%
INFO:ArmchairExpert:Training_Preprocessing_Structure(Import)
INFO:ArmchairExpert:Training_Preprocessing_Structure(Twitter)
INFO:ArmchairExpert:Training_Preprocessing_Structure(Twitter): 0.000000%
INFO:ArmchairExpert:Training_Preprocessing_Structure(Twitter): 0.302078%
INFO:ArmchairExpert:Training_Preprocessing_Structure(Twitter): 0.604157%
```

Did you see the part about Training_Processing_Structure? Or the part where it actually got to the training? If not you could try and launch the bot with retraining flags just to make sure this ran ok:
`python armchair_expert.py --retrain-markov --retrain-structure`

**Comment by Atropha** [comment]
Yeah, I fed it a whole bunch of data. It did most of it's processing, although seemed to stop at around 15% of processing structure. It didn't spit out any errors, so I figured it worked anyway. I'll try retraining it with a more limited data set just for testing purposes.

**Comment by csvance** [comment]
Its normal that it stops at 15% actually depending on how much data you fed it. Because the sentence structure neural network can take a long time to train and the diminishing returns more data provides for most use cases, I limited it to processing 250000 lines by default (I probably should randomize which lines are selected in the future). There is no such limit on the markov chain training however. You can change this if you want in config/ml.py: STRUCTURE_MODEL_TRAINING_MAX_SIZE

Curious, when you mention the bot does something like this print out in the console the first time:
```
RuntimeWarning: invalid value encountered in true_divide
  p_values = distance_magnitudes / sums

```

Its harmless and I need to get around to fixing it, but it means the bot definitely got the message and at least tried to formulate a response.

**Comment by csvance** [comment]
Might also be worth running https://github.com/csvance/armchair-expert/blob/master/scripts/generate_text.py to see if it is able to generate with what you trained it with. Set some words for it to generate from on the line that says `for word in ['Some', 'Words', 'Here']:`

**Comment by Atropha** [comment]
It retrained just fine, but then it just sits there. It joins the Discord server but that's about it. I also noticed that aol-reaction-model.h5 is missing from the weights folder. It generated the other ones, but I figure without that it's not going to work correctly.

Using generate_text.py spits out this:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\Barrin\Anaconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\Barrin\Anaconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\Barrin\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\DiscordBot\Armchair2\generate_text.py", line 14, in <module>
>     structure_model.start()
>   File "C:\DiscordBot\Armchair2\models\model_common.py", line 12, in start
>     self._worker.start()
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\process.py", line 105, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
>     _check_not_importing_main()
>   File "C:\Users\Barrin\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.

**Comment by csvance** [comment]
aol-reaction-model.h5 isn't currently used. Do you see the bot as online in discord?

**Comment by Atropha** [comment]
Yeah. The only time I see anything in the command prompt happen is when I try to PM it, in which case it produces this:

> Traceback (most recent call last):
>   File "C:\Users\Barrin\Anaconda3\lib\site-packages\discord\client.py", line 307, in _run_event
>     yield from getattr(self, event)(*args, **kwargs)
>   File "C:\DiscordBot\Armchair2\connectors\discord.py", line 53, in on_message
>     DiscordTrainingDataManager().store(message)
>   File "C:\DiscordBot\Armchair2\storage\discord.py", line 48, in store
>     message = DiscordMessage(server_id=int(message.server.id), channel_id=int(message.channel.id), user_id=int(message.author.id), timestamp=message.timestamp, text=filtered_content.encode())
> AttributeError: 'NoneType' object has no attribute 'id'

**Comment by csvance** [comment]
Ok, now we are onto something. I *think* I fixed the generate_text.py script, it suffered from a similar issue as the one you initially reported (sloppiness on my part dealing with multiprocessing)

I get the same error mentioning it in private message, this wasn't an original use case so I guess it was never tested. I will get that fixed.

Can you try mentioning it in a channel on a server?

**Comment by Atropha** [comment]
Yeah, I figured it was having trouble figuring what to do with the PM input. When I @ it in a channel nothing happens. The command prompt just sits idle(?) on this:

> INFO:ArmchairExpert:Status: STARTING_UP
> C:\Users\Barrin\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Using TensorFlow backend.
> _________________________________________________________________
> Layer (type)                 Output Shape              Param #
> =================================================================
> embedding_1 (Embedding)      (None, 16, 120)           14400
> _________________________________________________________________
> lstm_1 (LSTM)                (None, 16, 128)           127488
> _________________________________________________________________
> lstm_2 (LSTM)                (None, 128)               131584
> _________________________________________________________________
> dense_1 (Dense)              (None, 120)               15480
> =================================================================
> Total params: 288,952
> Trainable params: 288,952
> Non-trainable params: 0
> _________________________________________________________________
> 2018-02-20 18:27:06.087597: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
> INFO:ArmchairExpert:Loaded Discord Connector.
> INFO:ArmchairExpert:Loading spaCy model
> INFO:ArmchairExpert:Training begin
> INFO:ArmchairExpert:Training_Preprocessing_Markov(Import)
> INFO:ArmchairExpert:Training_Preprocessing_Markov(Discord)
> INFO:ArmchairExpert:Training(Markov)
> INFO:ArmchairExpert:Training end
> INFO:ArmchairExpert:Status: RUNNING

**Comment by csvance** [comment]
Are you sure you have config/discord.py DISCORD_USERNAME set correctly? The format is like this 'SomeBot#1234' you can see the username by clicking on the bots name while in private message or in the server list.

I just submitted a few patches that fix the crashes in private messages.

The bot won't reply unless it knows the words it considers topics in your message. So try asking it generic things, like `@Bot words you should know`

**Comment by Atropha** [comment]
Yeah, the username's set in the discord config. It's possible I just haven't hit the right topic yet. I've mostly just thrown random lines at it. I'll see if I can be a bit more specific.

**Comment by csvance** [comment]
With alot of data usually you don't need to be terribly specific, but it will always have an easier time generating responses to queries which include things like nouns and verbs that it sees alot in training data.

By default, it picks two words from the sentence in this order of descending priority: [Pos.HASHTAG, Pos.PROPN, Pos.NOUN, Pos.VERB, Pos.EMOJI, Pos.URL, Pos.ADJ, Pos.ADV, Pos.NUM, Pos.X, Pos.INTJ]

Question, is your training data in english or another language? A different spaCy model would need to be loaded for another language. I have been wanting to add support for this as it wouldn't be a difficult change, provided the people who develop spaCy have trained a model for the language in question.

**Comment by Atropha** [comment]
It's in English. It's also possible that I messed up inputting the data somehow. I dragged the import_text_file.py into the main directory and executed it pointing it at a plain .txt file in the same folder.

**Comment by csvance** [comment]
That sounds ok to me. Maybe you could try one of my known working databases and see if the bot will respond? This one is for better or worse trained off of all Donald Trump's tweets (the idea originally was to make something like DeepDrumpf without the specialized training data, instead only using his tweets)

Backup your weights folder, then copy the files from the archive in and try running the bot again. 

https://www.dropbox.com/s/3iso2uf0y6ghsbs/weights.zip?dl=0

**Comment by Atropha** [comment]
Yep, it responds when I use the Trump weights.
Well, at least now I know that the problem is what I'm training it on and can experiment with that.
Thanks so much for taking the time to troubleshoot this!

**Comment by csvance** [comment]
No problem, I know its a bit rough around in the edges in some places and will work on making it a bit more user friendly. Any and all feedback is very much appreciated.
